/**
 * DISPEX API Test - V3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BindClientDto model module.
 * @module model/BindClientDto
 * @version 3.0
 */
class BindClientDto {
    /**
     * Constructs a new <code>BindClientDto</code>.
     * @alias module:model/BindClientDto
     */
    constructor() { 
        
        BindClientDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BindClientDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BindClientDto} obj Optional instance to populate.
     * @return {module:model/BindClientDto} The populated <code>BindClientDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindClientDto();

            if (data.hasOwnProperty('addressId')) {
                obj['addressId'] = ApiClient.convertToType(data['addressId'], 'Number');
            }
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BindClientDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BindClientDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} addressId
 */
BindClientDto.prototype['addressId'] = undefined;

/**
 * @member {Number} clientId
 */
BindClientDto.prototype['clientId'] = undefined;






export default BindClientDto;

