/**
 * DISPEX API Test - V3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BindArrearDto model module.
 * @module model/BindArrearDto
 * @version 3.0
 */
class BindArrearDto {
    /**
     * Constructs a new <code>BindArrearDto</code>.
     * @alias module:model/BindArrearDto
     */
    constructor() { 
        
        BindArrearDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BindArrearDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BindArrearDto} obj Optional instance to populate.
     * @return {module:model/BindArrearDto} The populated <code>BindArrearDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindArrearDto();

            if (data.hasOwnProperty('addressId')) {
                obj['addressId'] = ApiClient.convertToType(data['addressId'], 'Number');
            }
            if (data.hasOwnProperty('typeId')) {
                obj['typeId'] = ApiClient.convertToType(data['typeId'], 'Number');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BindArrearDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BindArrearDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['account'] && !(typeof data['account'] === 'string' || data['account'] instanceof String)) {
            throw new Error("Expected the field `account` to be a primitive type in the JSON string but got " + data['account']);
        }

        return true;
    }


}



/**
 * @member {Number} addressId
 */
BindArrearDto.prototype['addressId'] = undefined;

/**
 * @member {Number} typeId
 */
BindArrearDto.prototype['typeId'] = undefined;

/**
 * @member {String} account
 */
BindArrearDto.prototype['account'] = undefined;






export default BindArrearDto;

