/**
 * DISPEX API Test - V3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FlatDto model module.
 * @module model/FlatDto
 * @version 3.0
 */
class FlatDto {
    /**
     * Constructs a new <code>FlatDto</code>.
     * @alias module:model/FlatDto
     */
    constructor() { 
        
        FlatDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FlatDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FlatDto} obj Optional instance to populate.
     * @return {module:model/FlatDto} The populated <code>FlatDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FlatDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('flat')) {
                obj['flat'] = ApiClient.convertToType(data['flat'], 'String');
            }
            if (data.hasOwnProperty('typeId')) {
                obj['typeId'] = ApiClient.convertToType(data['typeId'], 'Number');
            }
            if (data.hasOwnProperty('typeName')) {
                obj['typeName'] = ApiClient.convertToType(data['typeName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FlatDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FlatDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['flat'] && !(typeof data['flat'] === 'string' || data['flat'] instanceof String)) {
            throw new Error("Expected the field `flat` to be a primitive type in the JSON string but got " + data['flat']);
        }
        // ensure the json data is a string
        if (data['typeName'] && !(typeof data['typeName'] === 'string' || data['typeName'] instanceof String)) {
            throw new Error("Expected the field `typeName` to be a primitive type in the JSON string but got " + data['typeName']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
FlatDto.prototype['id'] = undefined;

/**
 * @member {String} flat
 */
FlatDto.prototype['flat'] = undefined;

/**
 * @member {Number} typeId
 */
FlatDto.prototype['typeId'] = undefined;

/**
 * @member {String} typeName
 */
FlatDto.prototype['typeName'] = undefined;

/**
 * @member {String} name
 */
FlatDto.prototype['name'] = undefined;






export default FlatDto;

