/**
 * DISPEX API Test - V3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebHouseTypeDto from './WebHouseTypeDto';

/**
 * The WebHouseDto model module.
 * @module model/WebHouseDto
 * @version 3.0
 */
class WebHouseDto {
    /**
     * Constructs a new <code>WebHouseDto</code>.
     * @alias module:model/WebHouseDto
     */
    constructor() { 
        
        WebHouseDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebHouseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebHouseDto} obj Optional instance to populate.
     * @return {module:model/WebHouseDto} The populated <code>WebHouseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebHouseDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = WebHouseTypeDto.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebHouseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebHouseDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `type`
        if (data['type']) { // data not null
          WebHouseTypeDto.validateJSON(data['type']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
WebHouseDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
WebHouseDto.prototype['name'] = undefined;

/**
 * @member {module:model/WebHouseTypeDto} type
 */
WebHouseDto.prototype['type'] = undefined;






export default WebHouseDto;

