/**
 * DISPEX API Test - V3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DispexApiTestV30);
  }
}(this, function(expect, DispexApiTestV30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DispexApiTestV30.HousingStockApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HousingStockApi', function() {
    describe('housingStockAccountIdDelete', function() {
      it('should call housingStockAccountIdDelete successfully', function(done) {
        //uncomment below and update the code to test housingStockAccountIdDelete
        //instance.housingStockAccountIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockAccountPut', function() {
      it('should call housingStockAccountPut successfully', function(done) {
        //uncomment below and update the code to test housingStockAccountPut
        //instance.housingStockAccountPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockAccountTypesGet', function() {
      it('should call housingStockAccountTypesGet successfully', function(done) {
        //uncomment below and update the code to test housingStockAccountTypesGet
        //instance.housingStockAccountTypesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockBindClientIdDelete', function() {
      it('should call housingStockBindClientIdDelete successfully', function(done) {
        //uncomment below and update the code to test housingStockBindClientIdDelete
        //instance.housingStockBindClientIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockBindClientPut', function() {
      it('should call housingStockBindClientPut successfully', function(done) {
        //uncomment below and update the code to test housingStockBindClientPut
        //instance.housingStockBindClientPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockClientGet', function() {
      it('should call housingStockClientGet successfully', function(done) {
        //uncomment below and update the code to test housingStockClientGet
        //instance.housingStockClientGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockClientPost', function() {
      it('should call housingStockClientPost successfully', function(done) {
        //uncomment below and update the code to test housingStockClientPost
        //instance.housingStockClientPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockClientsGet', function() {
      it('should call housingStockClientsGet successfully', function(done) {
        //uncomment below and update the code to test housingStockClientsGet
        //instance.housingStockClientsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('housingStockGet', function() {
      it('should call housingStockGet successfully', function(done) {
        //uncomment below and update the code to test housingStockGet
        //instance.housingStockGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
