/**
 * DISPEX API Test - V3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DispexApiTestV30);
  }
}(this, function(expect, DispexApiTestV30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DispexApiTestV30.RequestApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RequestApi', function() {
    describe('requestHouseFlatsIdGet', function() {
      it('should call requestHouseFlatsIdGet successfully', function(done) {
        //uncomment below and update the code to test requestHouseFlatsIdGet
        //instance.requestHouseFlatsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestHousesIdGet', function() {
      it('should call requestHousesIdGet successfully', function(done) {
        //uncomment below and update the code to test requestHousesIdGet
        //instance.requestHousesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestStreetsGet', function() {
      it('should call requestStreetsGet successfully', function(done) {
        //uncomment below and update the code to test requestStreetsGet
        //instance.requestStreetsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
